"""Phase 2: Auto-synced MCP Resources.

Each resource reads from a LIVE source — FastAPI's app.openapi(), the
filesystem (markdown docs), or runtime introspection (Pydantic models,
provider config). No caching, no manual sync. When code changes, the
next resource query returns fresh data.

All resources are read-only. None make HTTP calls, none write to DB,
none have side effects.
"""

from __future__ import annotations

import glob
import json
import os
from pathlib import Path

from .server import mcp

_DOCS_DIR = Path(__file__).resolve().parent.parent.parent / "docs"


def _latest_doc_file(pattern: str) -> Path | None:
    """Find the newest dated markdown file matching the pattern."""
    files = sorted(_DOCS_DIR.glob(pattern))
    return files[-1] if files else None


# ---------------------------------------------------------------------------
# OpenAPI resources
# ---------------------------------------------------------------------------

@mcp.resource("openapi://full")
def openapi_full() -> str:
    """Complete OpenAPI 3.1 specification for the entire API.

    Auto-generated by FastAPI from the running application. Includes every
    route, parameter, request body, response schema, and error code.
    Refreshes automatically when endpoints are added or modified — just
    restart the service.

    This is the single source of truth for the API surface. Use it to
    discover every available endpoint and its exact parameter types.
    """
    from main import app
    return json.dumps(app.openapi(), indent=2)


@mcp.resource("openapi://endpoints")
def openapi_endpoints() -> str:
    """Condensed endpoint index: one line per route.

    Format: ``METHOD path — summary``
    Sorted alphabetically by path. Useful for quick scanning of the
    full API surface without parsing the complete OpenAPI spec.
    """
    from main import app
    spec = app.openapi()
    lines: list[str] = ["# API Endpoint Index", ""]
    for path in sorted(spec.get("paths", {})):
        for method, details in spec["paths"][path].items():
            if method.startswith("x-"):
                continue
            summary = details.get("summary", "")
            tag = (details.get("tags") or [""])[0]
            lines.append(f"- **{method.upper()}** `{path}` — {summary} _({tag})_")
    lines.append(f"\n**Total:** {len(lines) - 2} endpoints")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Documentation resources
# ---------------------------------------------------------------------------

@mcp.resource("docs://clay-guide")
def docs_clay_guide() -> str:
    """Clay enrichment step-by-step guide (latest version).

    The user-facing documentation for setting up the enrichment API in
    Clay tables. Includes input mode selection, field mapping, provider
    selection, authentication, and troubleshooting.

    This file is hand-maintained and dated. The MCP always serves the
    newest version from the ``docs/`` folder.
    """
    f = _latest_doc_file("ListBuilding_Clay_Enrichment_Guide_*.md")
    if not f:
        return "No Clay guide found in docs/."
    return f.read_text()


@mcp.resource("docs://api-reference")
def docs_api_reference() -> str:
    """Full platform API reference (latest version).

    Comprehensive documentation of every user-facing endpoint: enrichment,
    phone enrichment, scraper, auth, API keys, rate limits, UI features,
    and error codes. This is the canonical reference for integrators.

    Hand-maintained and dated. The MCP always serves the newest version.
    """
    f = _latest_doc_file("ListBuilding_Platform_Full_API_Reference_*.md")
    if not f:
        return "No API reference found in docs/."
    return f.read_text()


@mcp.resource("docs://changelog")
def docs_changelog() -> str:
    """Changelog extracted from the API reference.

    Shows what changed and when, from the original SOP (April 2026) to
    the latest update. Useful for understanding recent additions like
    selected_providers, SmartProspect integration, and the 0-email
    warning system.
    """
    f = _latest_doc_file("ListBuilding_Platform_Full_API_Reference_*.md")
    if not f:
        return "No changelog available."
    text = f.read_text()
    # Extract the Changelog section
    if "## Changelog" in text:
        start = text.index("## Changelog")
        return text[start:]
    return "No changelog section found in API reference."


# ---------------------------------------------------------------------------
# Provider status (live)
# ---------------------------------------------------------------------------

@mcp.resource("providers://status")
def providers_status() -> str:
    """Live provider cascade status.

    Shows which enrichment providers are currently enabled, their position
    in the cascade, and their rate limits. Reflects the current running
    state — if a provider is disabled via ``providers.py`` or env var,
    it shows as disabled here.

    Cascade order: Contacts DB → Blitz → SmartProspect → WizLeads → BetterEnrich.
    The cascade stops at the first provider that returns a valid email.
    """
    from enrichment import providers as prov

    cascade = [
        (1, "contacts_db", "75 RPS", "Free — internal database"),
        (2, "blitz", "25 RPS", "Paid — LinkedIn enrichment"),
        (3, "smartprospect", "30 RPS", "Paid — SmartLead Find Emails"),
        (4, "wizleads", "10 RPS", "Paid — verified email"),
        (5, "better_enrich", "10 RPS", "Paid — person + company email"),
    ]

    lines = [
        "# Provider Cascade Status (Live)",
        "",
        "| # | Provider | Status | Rate | Purpose |",
        "|---|----------|--------|------|---------|",
    ]
    for pos, name, rps, purpose in cascade:
        enabled = prov.is_provider_enabled(name)
        status = "✅ Enabled" if enabled else "❌ Disabled"
        lines.append(f"| {pos} | `{name}` | {status} | {rps} | {purpose} |")

    lines.extend([
        "",
        "**Valid provider names for `selected_providers`:** "
        "`contacts_db`, `blitz`, `smartprospect`, `wizleads`, `better_enrich`",
        "",
        "**Note:** `contacts_db` is always allowed even when not explicitly "
        "listed in `selected_providers` (mandatory first step).",
    ])
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Pydantic schema resources
# ---------------------------------------------------------------------------

@mcp.resource("schemas://{model_name}")
def get_schema(model_name: str) -> str:
    """JSON schema for any Pydantic request model.

    Returns the full ``model_json_schema()`` output — every field, type,
    default, and validation rule. Useful for constructing valid API
    requests without guessing parameter names.

    Available models:
    - ``UnifiedEnrichRequest`` — POST /api/enrichment/enrich
    - ``StartJobRequest`` — POST /api/enrichment/jobs (legacy)
    - ``ProviderToggleRequest`` — POST /api/enrichment/flows/domain-enrich
    - ``LinkedInV2Request`` — POST /api/enrichment/by-linkedin-v2
    - ``CompanySearchRequest`` — POST /api/enrichment/search/companies

    Args:
        model_name: The Pydantic class name (case-sensitive).
    """
    from enrichment import routes as enr

    model_map = {
        "UnifiedEnrichRequest": enr.UnifiedEnrichRequest,
        "StartJobRequest": enr.StartJobRequest,
        "ProviderToggleRequest": enr.ProviderToggleRequest,
        "LinkedInV2Request": enr.LinkedInV2Request,
        "CompanySearchRequest": enr.CompanySearchRequest,
    }

    if model_name not in model_map:
        available = "\n".join(f"  - `{n}`" for n in sorted(model_map))
        return f"Unknown model `{model_name}`.\n\nAvailable models:\n{available}"

    schema = model_map[model_name].model_json_schema()
    return json.dumps(schema, indent=2)
